services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    command: python -m uvicorn api.main:app --host 0.0.0.0 --port 8000

  dashboard:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    command: streamlit run dashboard/streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    depends_on:
      - api